import React, { useContext, useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { Store } from "../utils/Store";
import Image from "next/image";

export default function Layout({ title, children }) {
  const { state, dispatch } = useContext(Store);

  const { cart } = state;

  const [cartItemsCount, setcartItemsCount] = useState(0);

  useEffect(() => {
    setcartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);

  return (
    <div>
      <Head>
        <title>{title ? "Barkery - " + title : "Barkery"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <div className="container">
          <Link href="/" className="navbar-brand">
            <Image
              src="/barkery-logo.jpg"
              alt="BARKERY - Pet Shop"
              width={50}
              height={60}
            />
          </Link>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav ms-auto">
              <li className="nav-item">
                <Link href="/cart" className="nav-link">
                  Cart
                  <span className="text-white bg-danger rounded p-1">
                    {cartItemsCount}
                  </span>
                </Link>
              </li>

              <li className="nav-item">
                <Link href="" className="nav-link">
                  Others
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <main>{children}</main>
    </div>
  );
}
