export const data = {
  products: [
    {
      id: 1,
      name: "Correa con soporte para pasear a nuestros amigos caninos",
      description:
        "Super Segura, con correa extendible, realizada con materiales reciclados",
      image: "/bark-02-dogleash-support.jpg",
      price: 35000,
      quantity: 5,
      countInStock: 10,
      offer: 0.25,
      category: "Perros",
      rating: 5,
      numReviews: 10,
      slug: "correa soporte",
    },
    {
      id: 2,
      name: "Mochila para llevar mascotas pequeñas/como gatos",
      description:
        "Confeccionada por abuelas del Noreste Argentino, super liviana y flexible, lista para llevar a todas partes",
      image: "/bark-01-catbackpack.jpg",
      price: 25000,
      quantity: 4,
      countInStock: 10,
      offer: 1,
      category: "Gatos",
      rating: 5,
      numReviews: 10,
      slug: "mochila mascota",
    },
    {
      id: 3,
      name: "Cama moderna, ideal para mascotas pequeñas",
      description:
        "Super contemporánea, y muy original, ideal para quienes buscan un estilo de decoración moderno",
      image: "/bark-23-catbed2.jpg",
      price: 55000,
      quantity: 4,
      countInStock: 10,
      offer: 0.2,
      category: "Gatos",
      rating: 4,
      numReviews: 10,
      slug: "cama moderna",
    },
    {
      id: 4,
      name: "Pecera de vidrio acojedora adaptable a lugares pequeños",
      description:
        "Este estilo de pecera no desilusiona, siempre vigente para admirar a nuestros peces amigos.",
      image: "/bark-05-fishbowl.jpg",
      price: 45000,
      quantity: 8,
      countInStock: 10,
      offer: 0.2,
      category: "Peces",
      rating: 5,
      numReviews: 10,
      slug: "pecera bowl",
    },
    {
      id: 5,
      name: "Alimentador con néctar para pájaros",
      description:
        "Fácil de instalar, es un atractivo para ver alimentarse desde tu ventana, aves de distintos tipos y colores. Un sueño!.",
      image: "/bark-04-birdfeeder.jpg",
      price: 35000,
      quantity: 0.2,
      countInStock: 10,
      offer: 1,
      category: "Pájaros",
      rating: 3,
      numReviews: 10,
      slug: "alimentador pajaro",
    },
    {
      id: 6,
      name: "Doble set of bowls para perros",
      description:
        "Realizado completamente con productos reciclados, este estilo de bowls es perfecto para adornar cualquier ambiente.",
      image: "/bark-03-dogbowls.jpg",
      price: 32000,
      quantity: 7,
      countInStock: 10,
      offer: 0.2,
      category: "Perros",
      rating: 5,
      numReviews: 10,
      slug: "bowls perros",
    },
    {
      id: 7,
      name: "Alimento orgánico para perros",
      description:
        "Ingrededientes de alta calidad, desarrollado por un grupo de nutricionistas locales. Se vende por kilo.",
      image: "/bark-06-dogfood.jpg",
      price: 5000,
      quantity: 9,
      countInStock: 10,
      offer: 1,
      category: "Perros",
      rating: 5,
      numReviews: 10,
      slug: "alimento perro",
    },
    {
      id: 8,
      name: "Alimento orgánico para gatos",
      description:
        "Ingrededientes de alta calidad, desarrollado por un grupo de nutricionistas locales. Se vende por kilo.",
      image: "/bark-07-catfood.jpeg",
      price: 5000,
      quantity: 10,
      countInStock: 10,
      offer: 1,
      category: "Gatos",
      rating: 5,
      numReviews: 10,
      slug: "alimento gatos",
    },
    {
      id: 9,
      name: "Alimento orgánico para pájaros",
      description:
        "Ingrededientes de alta calidad, desarrollado por un grupo de nutricionistas locales. Se vende por 100 gramos.",
      image: "/bark-08-birdfood.jpeg",
      price: 3000,
      quantity: 5,
      countInStock: 10,
      offer: 1,
      category: "Pájaros",
      rating: 4,
      numReviews: 10,
      slug: "alimento pájaros",
    },
    {
      id: 10,
      name: "Alimento orgánico para peces",
      description:
        "Ingrededientes de alta calidad, desarrollado por un grupo de nutricionistas locales. Se vende por 100 gramos.",
      image: "/bark-09-fishfood.jpg",
      price: 2000,
      quantity: 5,
      countInStock: 10,
      offer: 1,
      category: "Peces",
      rating: 3,
      numReviews: 10,
      slug: "alimento peces",
    },
    {
      id: 11,
      name: "Alimento orgánico para hamsters",
      description:
        "Ingrededientes de alta calidad, desarrollado por un grupo de nutricionistas locales. Se vende por 100 gramos.",
      image: "/bark-10-hamsterfood.jpg",
      price: 3500,
      quantity: 1,
      countInStock: 10,
      offer: 1,
      category: "Hamsters",
      rating: 4,
      numReviews: 10,
      slug: "alimento hamster",
    },
    {
      id: 12,
      name: "Cama peluda para nuestros amigos caninos",
      description:
        "Realizado completamente con productos reciclados, este estilo de cama es perfecto para adornar cualquier ambiente.",
      image: "/bark-16-dogbed1.jpg",
      price: 38000,
      quantity: 2,
      countInStock: 10,
      offer: 0.2,
      category: "Perros",
      rating: 5,
      numReviews: 10,
      slug: "cama peluda",
    },
    {
      id: 13,
      name: "Cama estilo cueva a para nuestros amigos felinos",
      description:
        "Realizado completamente con productos reciclados, este estilo de cama/cueva es perfecto para adornar cualquier ambiente.",
      image: "/bark-24-catbed3.jpeg",
      price: 28000,
      quantity: 3,
      countInStock: 10,
      offer: 0.2,
      category: "Gatos",
      rating: 5,
      numReviews: 10,
      slug: "cama cueva",
    },
    {
      id: 14,
      name: "Cama canasto a para nuestros amigos caninos",
      description:
        "Realizado completamente con productos reciclados, este estilo de canastos es perfecto para adornar cualquier ambiente.",
      image: "/bark-18-dogbed3.jpg",
      price: 25000,
      quantity: 5,
      countInStock: 10,
      offer: 1,
      category: "Perros",
      rating: 5,
      numReviews: 10,
      slug: "cama canasto",
    },
    {
      id: 15,
      name: "Laberinto juguete para hamsters.",
      description:
        "Realizado completamente con productos reciclados, entretenimiento para hamsters es super original.",
      image: "/bark-11-hamstermaze.jpg",
      price: 15000,
      quantity: 2,
      countInStock: 10,
      offer: 15,
      category: "Hamsters",
      rating: 3,
      numReviews: 10,
      slug: "juguete hamster",
    },
    {
      id: 16,
      name: "Espectacular pecera iluminada",
      description:
        "Realizado completamente con productos reciclados, esta vibrante pecera realza cualquier ambiente de la casa",
      image: "/bark-13-fishtank.jpeg",
      price: 75000,
      quantity: 2,
      countInStock: 10,
      offer: 25,
      category: "Peces",
      rating: 4,
      numReviews: 10,
      slug: "pecera iluminada",
    },
    {
      id: 17,
      name: "Jaula abierta para pájaros",
      description:
        "Realizado completamente con productos reciclados, esta hermosa jaula ofrece a nuestras aves mascotas la opción de entrar y salir cuando les plazca.",
      image: "/bark-14-birdcagenodoor.jpg",
      price: 55000,
      quantity: 4,
      countInStock: 10,
      offer: 20,
      category: "Pájaros",
      rating: 5,
      numReviews: 10,
      slug: "jaula pajaros",
    },
    {
      id: 18,
      name: "Soga trenzada para pájaros",
      description:
        "Realizado completamente con productos reciclados, un lugar de descanso para aves.",
      image: "/bark-15-birdrope.jpg",
      price: 25000,
      quantity: 1,
      countInStock: 10,
      offer: 1,
      category: "Pájaros",
      rating: 4,
      numReviews: 10,
      slug: "soga pajaros",
    },
    {
      id: 19,
      name: "Casa de mimbre para perros",
      description:
        "Realizado completamente con productos reciclados, un estilo mu especial para nuestros amigos caninos.",
      image: "/bark-17-dogbed2.jpg",
      price: 75000,
      quantity: 4,
      countInStock: 10,
      offer: 1,
      category: "Perros",
      rating: 4,
      numReviews: 10,
      slug: "cucha mimbre",
    },

    {
      id: 20,
      name: "Mochila para transportar mascotas pequeñas, ideal para perros.",
      description:
        "Realizado completamente con productos reciclados, fácil de acarrear a nuestros amigos caninos.",
      image: "/bark-19-dogcarseat.jpg",
      price: 45000,
      quantity: 6,
      countInStock: 10,
      offer: 1,
      category: "Perros",
      rating: 5,
      numReviews: 10,
      slug: "mochila auto",
    },
    {
      id: 21,
      name: "Círculo juguete para perros",
      description:
        "Realizado completamente con productos reciclados, ideal para juguetes caninos.",
      image: "/bark-19-dogcarseat.jpg",
      price: 15000,
      quantity: 4,
      countInStock: 10,
      offer: 1,
      category: "Perros",
      rating: 4,
      numReviews: 10,
      slug: "juguete perros",
    },
    {
      id: 22,
      name: "Bolas juguete para gatos",
      description:
        "Realizado completamente con productos reciclados, ideal para juguetes felinos",
      image: "/bark-21-dogtoy2.jpg",
      price: 20000,
      quantity: 2,
      countInStock: 10,
      offer: 1,
      category: "Gatos",
      rating: 4,
      numReviews: 10,
      slug: "juguete gatos",
    },
    {
      id: 23,
      name: "Cama sillón a para nuestros amigos felinos",
      description:
        "Realizado completamente con productos reciclados, este estilo de cama es perfecto para desacanso gatuno.",
      image: "/bark-22-catbed1.jpeg",
      price: 35000,
      quantity: 4,
      countInStock: 10,
      offer: 0.2,
      category: "Gatos",
      rating: 4,
      numReviews: 10,
      slug: "sillon gatos",
    },
    {
      id: 24,
      name: "Silla para coche, para transportar a nuestras mascotas felinas.",
      description:
        "Realizado completamente con productos reciclados, fácil de acarrear para seguridad de todos los gatos.",
      image: "/bark-25-catseat.jpg",
      price: 45000,
      quantity: 2,
      countInStock: 10,
      offer: 1,
      category: "Gatos",
      rating: 4,
      numReviews: 10,
      slug: "silla coche",
    },
    {
      id: 25,
      name: "Ratita de juguete para gatos",
      description:
        "Realizado completamente con productos reciclados, ideal para juguetes felinos",
      image: "/bark-27-cattoy2.jpg",
      price: 25000,
      quantity: 3,
      countInStock: 10,
      offer: 1,
      category: "Gatos",
      rating: 4,
      numReviews: 10,
      slug: "rata juguete",
    },
    {
      id: 26,
      name: "Doble set of bowls para gatos",
      description:
        "Realizado completamente con productos reciclados, este estilo de bowls es perfecto para adornar cualquier ambiente.",
      image: "/bark-28-cat-bowls.jpg",
      price: 28000,
      quantity: 7,
      countInStock: 10,
      offer: 1,
      category: "Gatos",
      rating: 5,
      numReviews: 10,
      slug: "bowls gatos",
    },
  ],
};
